AutoStart1:
  Hora: '0000'
  Comando: 'say teste'
AutoStart2:
  Hora: '0000'
  Comando: 'say teste'
AutoStart3:
  Hora: '0000'
  Comando: 'say teste'
AutoStart4:
  Hora: '0000'
  Comando: 'say teste'
AutoStart5:
  Hora: '0000'
  Comando: 'say teste'
AutoStart6:
  Hora: '0000'
  Comando: 'say teste'
AutoStart7:
  Hora: '0000'
  Comando: 'say teste'
AutoStart8:
  Hora: '0000'
  Comando: 'say teste'
AutoStart9:
  Hora: '0000'
  Comando: 'say teste'
AutoStart10:
  Hora: '0000'
  Comando: 'say teste'
AutoStart11:
  Hora: '0000'
  Comando: 'say teste'
AutoStart12:
  Hora: '0000'
  Comando: 'say teste'
AutoStart13:
  Hora: '0000'
  Comando: 'say teste'
AutoStart14:
  Hora: '0000'
  Comando: 'say teste'
AutoStart15:
  Hora: '0000'
  Comando: 'say teste'
AutoStart16:
  Hora: '0000'
  Comando: 'say teste'
AutoStart17:
  Hora: '0000'
  Comando: 'say teste'
AutoStart18:
  Hora: '0000'
  Comando: 'say teste'
AutoStart19:
  Hora: '0000'
  Comando: 'say teste'
AutoStart20:
  Hora: '0000'
  Comando: 'say teste'
AutoStart21:
  Hora: '0000'
  Comando: 'say teste'
AutoStart22:
  Hora: '0000'
  Comando: 'say teste'
AutoStart23:
  Hora: '0000'
  Comando: 'say teste'
AutoStart24:
  Hora: '0000'
  Comando: 'say teste'